export const aromatherapy = {
    topImg: '../../images/product/box/box.jpg',
    title: '内搭|香氛类',
    describe: '大海喷着白沫哈哈大笑，汹涌的波浪用奔放的旋律在他们耳中写—首歌曲，让人想起妈妈唱着歌儿，把摇篮轻轻的摇，大海和孩子们做游戏，平坦的沙难默默的笑。',
    detailImg: ['cloud://cloud1-9g318somea8c02f9.636c-cloud1-9g318somea8c02f9-1310275304/aromatherapy/1.jpg'],
}
export const washProtect = {
    topImg: '../../images/product/box/box.jpg',
    title: '内搭|个人洗护类',
    describe: '等一个冬日的春苏醒',
    detailImg: [
        'cloud://cloud1-9g318somea8c02f9.636c-cloud1-9g318somea8c02f9-1310275304/washProtect/1.jpg',
        'cloud://cloud1-9g318somea8c02f9.636c-cloud1-9g318somea8c02f9-1310275304/washProtect/2.jpg',
        'cloud://cloud1-9g318somea8c02f9.636c-cloud1-9g318somea8c02f9-1310275304/washProtect/4.jpg',
        'cloud://cloud1-9g318somea8c02f9.636c-cloud1-9g318somea8c02f9-1310275304/washProtect/5.jpg',
        'cloud://cloud1-9g318somea8c02f9.636c-cloud1-9g318somea8c02f9-1310275304/washProtect/6.jpg',
    ],
}
export const goodsList = [
    { id: 1,
    name: "全品类喜糖礼盒",
    scrollId: "s1",
    goods: [{ pic: '../../images/product/box/box.jpg',
        title: '内搭|香氛类',
        subtitle: '礼盒合集',
        id: 'aromatherapy'},
    { pic: '../../images/product/box/box.jpg',
        title: '内搭|个人洗护类',
        subtitle: '礼盒合集',
    id: 'washProtect'}] },
    { id: 2,
    name: "礼盒内搭合集",
    scrollId: "s2",
    goods: [{ pic: '../../images/product/box/box.jpg',
        title: '内搭|香氛类',
        subtitle: '礼盒合集',
        id: 'aromatherapy'},
    { pic: '../../images/product/box/box.jpg',
        title: '内搭|个人洗护类',
        subtitle: '礼盒合集',
    id: 'washProtect'}] },
    { id: 3,
    name: "伴郎伴郎礼",
    scrollId: "s3",
    goods: [{ pic: '../../images/product/box/box.jpg',
        title: '内搭|香氛类',
        subtitle: '礼盒合集',
        id: 'aromatherapy'},
    { pic: '../../images/product/box/box.jpg',
        title: '内搭|个人洗护类',
        subtitle: '礼盒合集',
    id: 'washProtect'}] },
    { id: 4,
    name: "白金色系伴手礼",
    scrollId: "s4",
    goods: [{ pic: '../../images/product/box/box.jpg',
        title: '内搭|香氛类',
        subtitle: '礼盒合集',
        id: 'aromatherapy'},
    { pic: '../../images/product/box/box.jpg',
        title: '内搭|个人洗护类',
        subtitle: '礼盒合集',
    id: 'washProtect'}] },
    { id: 5,
    name: "宝宝",
    scrollId: "s5",
    goods: [{ pic: '../../images/product/box/box.jpg',
        title: '内搭|香氛类',
        subtitle: '礼盒合集',
        id: 'aromatherapy'},
    { pic: '../../images/product/box/box.jpg',
        title: '内搭|个人洗护类',
        subtitle: '礼盒合集',
    id: 'washProtect'}] },
    { id: 6,
    name: "商务",
    scrollId: "s6",
    goods: [{ pic: '../../images/product/box/box.jpg',
        title: '内搭|香氛类',
        subtitle: '礼盒合集',
        id: 'aromatherapy'},
    { pic: '../../images/product/box/box.jpg',
        title: '内搭|个人洗护类',
        subtitle: '礼盒合集',
    id: 'washProtect'}] },
]